jinishkoi/catalog/urls.py
from nturl2path import url2pathname
from django.urls import URLPattern, path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('equipments/', views.EquipmentListView.as_view(), name='equipments'),
    path('equipment/<int:pk>', views.EquipmentDetailView.as_view(), name='equipment-detail'),
    path('stores/', views.StoreListView.as_view(), name='stores'),
    path('store/<int:pk>',
         views.StoreDetailView.as_view(), name='store-detail'),
]
urlpatterns += [
    path('myequipments/', views.LoanedEquipmentsByUserListView.as_view(), name='my-borrowed'),
    path(r'borrowed/', views.LoanedEquipmentsAllListView.as_view(), name='all-borrowed'),  # Added for challenge
]

urlpatterns += [
    path('equipment/<uuid:pk>/renew/', views.renew_equipment_storeman, name='renew-equipment-storeman'),
]

# Add URLConf to create, update, and delete stores
urlpatterns += [
    path('store/create/', views.StoreCreate.as_view(), name='store-create'),
    path('store/<int:pk>/update/', views.StoreUpdate.as_view(), name='store-update'),
    path('store/<int:pk>/delete/', views.StoreDelete.as_view(), name='store-delete'),
]

# Add URLConf to create, update, and delete equipments
urlpatterns += [
    path('equipment/create/', views.EquipmentCreate.as_view(), name='equipment-create'),
    path('equipment/<int:pk>/update/', views.EquipmentUpdate.as_view(), name='equipment-update'),
    path('equipment/<int:pk>/delete/', views.EquipmentDelete.as_view(), name='equipment-delete'),
]

jinishkoi/jinishkoi/urls.py
from os import stat
from xml.dom.minidom import Document
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

from django.urls import include
urlpatterns += [
    path('catalog/', include('catalog.urls')),
]


from django.views.generic import RedirectView
urlpatterns += [
    path('', RedirectView.as_view(url='catalog/', permanent=True)),
]

from django.conf import settings
from django.conf.urls.static import static

urlpatterns += static(settings.STATIC_URL,
Document_root=settings.STATIC_ROOT)

#Add Django site authentication urls (for login, logout, password management)

urlpatterns += [
    path('accounts/', include('django.contrib.auth.urls')),
]

jinishkoi/catalog/models.py
from audioop import reverse
from pyexpat import model
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import User
from datetime import date


# Create your models here.

class EquipmentType(models.Model):
    """Model representing a equipment type."""
    name = models.CharField(max_length=200, help_text='Enter a equipment type (e.g. Radio Set)')

    def __str__(self):
        """String for representing the Model object."""
        return self.name


class Equipment(models.Model):
    """Model  representing a equipment but not a specific copy of a equipment"""
    title = models.CharField(max_length=200)

    # Foreign Key used because book can only have one author, but authors can have multiple books
    # Author as a string rather than object because it hasn't been declared yet in the file
    store = models.ForeignKey('Store', on_delete=models.SET_NULL, null=True)

    summary = models.TextField(max_length=1000, help_text='Enter a brief description of the equipment')
    manufacture_id = models.CharField('Manufacture', max_length=13, unique=True,
                             help_text='Unique manufacture number')

    # ManyToManyField used because genre can contain many books. Books can cover many genres.
    # Genre class has already been defined so we can specify the object above.
    equipment_type = models.ManyToManyField(EquipmentType, help_text='Select a type for this equipment')


    class Meta:
        ordering = ['title', 'store']

    def __str__(self):
        """String for representing the Model object."""
        return self.title

    def get_absolute_url(self):
        """Returns the URL to access a detail record for this book."""
        return reverse('equipment-detail', args=[str(self.id)])

    def display_equipment_type(self):
        """Create a string for the Genre. This is required to display genre in Admin."""
        return ', '.join(equipment_type.name for equipment_type in self.equipment_type.all()[:3])

    display_equipment_type.short_description = 'Types'


import uuid # Required for unique equipment instances

class EquipmentInstance(models.Model):
    """Model representing a specific copy of a equipment (i.e. that can be borrowed from the store)."""
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, help_text='Unique ID for this particular equipment across whole institution')
    equipment = models.ForeignKey('Equipment', on_delete=models.RESTRICT, null=True)
    imprint = models.CharField(max_length=200)
    due_back = models.DateField(null=True, blank=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


    LOAN_STATUS = (
        ('m', 'Maintenance'),
        ('o', 'On loan'),
        ('a', 'Available'),
        ('r', 'Reserved'),
    )

    status = models.CharField(
        max_length=1,
        choices=LOAN_STATUS,
        blank=True,
        default='m',
        help_text='Equipment availability',
    )

    class Meta:
        ordering = ['due_back']
        permissions = (("can_mark_returned", "Set equipment as returned"),)

    def __str__(self):
        """String for representing the Model object."""
        return f'{self.id} ({self.equipment.title})'

    @property
    def is_overdue(self):
        if self.due_back and date.today() > self.due_back:
            return True
        return False


class Store(models.Model):
    """Model representing a store."""
    store_name = models.CharField(max_length=100)
    coy_name = models.CharField(max_length=100)
    date_of_last_maintainance = models.DateField(null=True, blank=True)
    date_of_next_maintainance = models.DateField('Maintainance', null=True, blank=True)

    class Meta:
        ordering = ['coy_name', 'store_name']

    def get_absolute_url(self):
        """Returns the URL to access a particular store instance."""
        return reverse('store-detail', args=[str(self.id)])

    def __str__(self):
        """String for representing the Model object."""
        return '{0}, {1}'.format(self.coy_name, self.store_name)

jinishkoi/catalog/forms.py
import datetime

from django import forms

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _

class RenewEquipmentForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data

jinishkoi/catalog/views.py
from django.shortcuts import render
from django.shortcuts import get_object_or_404
from django.views import generic

# Create your views here.
from .models import Equipment, Store, EquipmentInstance, EquipmentType

def index(request):
    """View function for home page of site."""

    # Generate counts of some of the main objects
    num_equipments = Equipment.objects.all().count()
    num_instances = EquipmentInstance.objects.all().count()

    # Available books (status = 'a')
    num_instances_available = EquipmentInstance.objects.filter(status__exact='a').count()

    # The 'all()' is implied by default.
    num_stores = Store.objects.count()


    # Number of visits to this view, as counted in the session variable.
    num_visits = request.session.get('num_visits', 0)
    request.session['num_visits'] = num_visits + 1


    context = {
        'num_equipments': num_equipments,
        'num_instances': num_instances,
        'num_instances_available': num_instances_available,
        'num_stores': num_stores,
        'num_visits': num_visits,
    }

    # Render the HTML template index.html with the data in the context variable
    return render(request, 'index.html', context=context)



class EquipmentListView(generic.ListView):
    model = Equipment
    paginate_by = 10


class EquipmentDetailView(generic.DetailView):
    model = Equipment
    paginate_by = 10

    def equipment_detail_view(request, primary_key):
        equipment = get_object_or_404(Equipment, pk=primary_key)
        return render(request, 'catalog/equipment_detail.html', context={'equipment': equipment})


class StoreListView(generic.ListView):
    """Generic class-based list view for a list of authors."""
    model = Store
    paginate_by = 10

class StoreDetailView(generic.DetailView):
    """Generic class-based detail view for an author."""
    model = Store


from django.contrib.auth.mixins import LoginRequiredMixin


class LoanedEquipmentsByUserListView(LoginRequiredMixin,generic.ListView):
    """Generic class-based view listing books on loan to current user."""
    model = EquipmentInstance
    template_name ='catalog/equipmentinstance_list_borrowed_user.html'
    paginate_by = 10

    def get_queryset(self):
        return EquipmentInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('due_back')

# Added as part of challenge!
from django.contrib.auth.mixins import PermissionRequiredMixin


class LoanedEquipmentsAllListView(PermissionRequiredMixin, generic.ListView):
    """Generic class-based view listing all equipments on loan. Only visible to users with can_mark_returned permission."""
    model = EquipmentInstance
    permission_required = 'catalog.can_mark_returned'
    template_name = 'catalog/equipmentinstance_list_borrowed_all.html'
    paginate_by = 10

    def get_queryset(self):
        return EquipmentInstance.objects.filter(status__exact='o').order_by('due_back')


import datetime

from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth.decorators import login_required, permission_required
from catalog.forms import RenewEquipmentForm


@login_required
@permission_required('catalog.can_mark_returned', raise_exception=True)
def renew_equipment_storeman(request, pk):
    equipment_instance = get_object_or_404(EquipmentInstance, pk=pk)

    # If this is a POST request then process the Form data
    if request.method == 'POST':

        # Create a form instance and populate it with data from the request (binding):
        form = RenewEquipmentForm(request.POST)

        # Check if the form is valid:
        if form.is_valid():
            # process the data in form.cleaned_data as required (here we just write it to the model due_back field)
            equipment_instance.due_back = form.cleaned_data['renewal_date']
            equipment_instance.save()

            # redirect to a new URL:
            return HttpResponseRedirect(reverse('all-borrowed') )

    # If this is a GET (or any other method) create the default form.
    else:
        proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
        form = RenewEquipmentForm(initial={'renewal_date': proposed_renewal_date})

    context = {
        'form': form,
        'equipment_instance': equipment_instance,
    }

    return render(request, 'catalog/equipment_renew_storeman.html', context)


from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .models import Store


class StoreCreate(PermissionRequiredMixin, CreateView):
    model = Store
    fields = ['store_name', 'coy_name', 'date_of_last_maintainance', 'date_of_next_maintainance']
    initial = {'date_of_next_maintainance': '11/06/2020'}
    permission_required = 'catalog.can_mark_returned'

class StoreUpdate(PermissionRequiredMixin, UpdateView):
    model = Store
    fields = '__all__' # Not recommended (potential security issue if more fields added)
    permission_required = 'catalog.can_mark_returned'


class StoreDelete(PermissionRequiredMixin, DeleteView):
    model = Store
    success_url = reverse_lazy('stores')
    permission_required = 'catalog.can_mark_returned'


# Classes created for the forms challenge
class EquipmentCreate(PermissionRequiredMixin, CreateView):
    model = Equipment
    fields = ['title', 'store', 'summary', 'manufacture_id', 'equipment_type']
    permission_required = 'catalog.can_mark_returned'


class EquipmentUpdate(PermissionRequiredMixin, UpdateView):
    model = Equipment
    fields = ['title', 'store', 'summary', 'manufacture_id', 'equipment_type']
    permission_required = 'catalog.can_mark_returned'


class EquipmentDelete(PermissionRequiredMixin, DeleteView):
    model = Equipment
    success_url = reverse_lazy('equipments')
    permission_required = 'catalog.can_mark_returned'

jinishkoi/catalog/templates/catalog/equipment_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Equipment</h1>

<p>Are you sure you want to delete the equipment: {{ equipment }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

jinishkoi/catalog/templates/catalog/equipment_detail.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Title: {{ equipment.title }}</h1>

  <p><strong>Store:</strong> <a href="">{{ equipment.store }}</a></p> <!-- store detail link not yet defined -->
  <p><strong>Summary:</strong> {{ equipment.summary }}</p>
  <p><strong>Manufacture ID:</strong> {{ equipment.manufacture_id }}</p>
  <!-- <p><strong>Language:</strong> {{ book.language }}</p> -->
  <p><strong>Type:</strong> {{ equipment.equipment_type.all|join:", " }}</p>

  <div style="margin-left:20px;margin-top:20px">
    <h4>Copies</h4>

    {% for copy in equipment.equipmentinstance_set.all %}
      <hr>
      <p class="{% if copy.status == 'a' %}text-success{% elif copy.status == 'm' %}text-danger{% else %}text-warning{% endif %}">
        {{ copy.get_status_display }}
      </p>
      {% if copy.status != 'a' %}
        <p><strong>Due to be returned:</strong> {{ copy.due_back }}</p>
      {% endif %}
      <p><strong>Imprint:</strong> {{ copy.imprint }}</p>
      <p class="text-muted"><strong>Id:</strong> {{ copy.id }}</p>
    {% endfor %}
  </div>
{% endblock %}

jinishkoi/catalog/templates/catalog/equipment_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

jinishkoi/catalog/templates/catalog/equipment_list.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Equipments List</h1>
  {% if equipment_list %}
  <ul>
    {% for equipment in equipment_list %}
      <li>
        <a href="{{ equipment.get_absolute_url }}">{{ equipment.title }}</a> ({{equipment.store}})
      </li>
    {% endfor %}
  </ul>
  {% else %}
    <p>There are no equipments in the stores.</p>
  {% endif %}
{% endblock %}

jinishkoi/catalog/templates/catalog/equipment_renew_storeman.html
{% extends "base_generic.html" %}

{% block content %}
  <h1>Renew: {{ equipment_instance.equipment.title }}</h1>
  <p>Borrower: {{ equipment_instance.borrower }}</p>
  <p{% if equipment_instance.is_overdue %} class="text-danger"{% endif %}>Due date: {{ equipment_instance.due_back }}</p>

  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

jinishkoi/catalog/templates/catalog/equipmentinstance_list_borrowed_all.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>All Borrowed Equipments</h1>

    {% if equipmentinstance_list %}
    <ul>

      {% for equipmentinst in equipmentinstance_list %} 
      <li class="{% if equipmentinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'equipment-detail' equipmentinst.equipment.pk %}">{{equipmentinst.equipment.title}}</a> ({{ equipmentinst.due_back }}) {% if user.is_staff %}- {{ equipmentinst.borrower }}{% endif %} {% if perms.catalog.can_mark_returned %}- <a href="{% url 'renew-equipment-storeman' equipmentinst.id %}">Renew</a>  {% endif %}
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no equipments borrowed.</p>
    {% endif %}       
{% endblock %}

jinishkoi/catalog/templates/catalog/equipmentinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Borrowed equipments</h1>

    {% if equipmentinstance_list %}
    <ul>

      {% for equipmentinst in equipmentinstance_list %}
      <li class="{% if equipmentinst.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'equipment-detail' equipmentinst.equipment.pk %}">{{equipmentinst.equipment.title}}</a> ({{ equipmentinst.due_back }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>There are no equipments borrowed.</p>
    {% endif %}
{% endblock %}

jinishkoi/catalog/templates/catalog/store_confirm_delete.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Delete Store</h1>

<p>Are you sure you want to delete the store: {{ store }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" action="" value="Yes, delete." />
</form>

{% endblock %}

jinishkoi/catalog/templates/catalog/store_detail.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Store: {{ store }} </h1>
<p>{{store.date_of_last_maintainance}} - {% if store.date_of_next_maintainance %}{{store.date_of_next_maintainance}}{% endif %}</p>

<div style="margin-left:20px;margin-top:20px">
<h4>Equipments</h4>

<dl>
{% for equipment in store.equipment_set.all %}
  <dt><a href="{% url 'equipment-detail' equipment.pk %}">{{equipment}}</a> ({{equipment.equipmentinstance_set.all.count}})</dt>
  <dd>{{equipment.summary}}</dd>
{% endfor %}
</dl>

</div>
{% endblock %}

jinishkoi/catalog/templates/catalog/store_form.html
{% extends "base_generic.html" %}

{% block content %}

<form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" />
    
</form>
{% endblock %}

jinishkoi/catalog/templates/catalog/store_list.html
{% extends "base_generic.html" %}

{% block content %}

<h1>Store List</h1>

{% if store_list %}
  <ul>

  {% for store in store_list %}
    <li>
      <a href="{{ store.get_absolute_url }}">
      {{ store }} ({{store.date_of_last_maintainance}} - {% if store.date_of_next_maintainance %}{{store.date_of_next_maintainance}}{% endif %})
      </a>
    </li>
  {% endfor %}

 </ul>
{% else %}
  <p>There are no stores available.</p>
{% endif %}
        
        
        
{% endblock %}